// window.onload = function () {
//   document.querySelector("h1").style.color = "blue";
// };
// console.log("%chey becarful,%ci wanna help you ","color: red ; font-size: 40px;","color: grey; font-size: 50px");
// console.log("This is a sample sentence with %ca specific word%c and the rest of the sentence.", "color: red; font-weight: bold;", "");
// document.write("<h1>Elzero</h1>");
// document.querySelector("h1").style.color ="blue";
// document.querySelector("h1").style="color: blue; font-size:"80px"; font-weight:"bold" ;text-align:"center";font-family:'arial'";
console.log("%cElzero %cWeb %cSchool", "color: red; font-size: 40px", "color: green; font-weight: bold; font-size: 40px; ", "color: white; background-color: blue; font-size: 40px;");
document.write("<h1>Elzero</h1>");
document.querySelector("h1").style.color = "blue";
document.querySelector("h1").style.fontSize = "80px";
document.querySelector("h1").style.fontWeight = "bold";
document.querySelector("h1").style.textAlign = "center";
document.querySelector("h1").style.family = "arial";
console.group("Group 1");
console.log("Message One");
console.log("Message Two");
console.group("Child Group");
console.log("Message One");
console.log("Message Two");
console.group("Grand Child Group");
console.log("Message One");
console.log("Message Two");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Group 2");
console.log("Message One");
console.log("Message Two");

